### ISSUE TITLE
Add input field for comment tag of changeset

### ISSUE THREAD

**Issue by yuiseki** [yuiseki/osm-address-editor-vite#7]
Split from: #4

OpenStreetMap Wiki says as below:

> Clients are advised to make sure that a [comment](https://wiki.openstreetmap.org/wiki/Key:comment)=* is present, which the user has entered. It is optional at the moment but this might change in later API versions. Clients should not automatically generate the comment tag, as this tag is for the end-user to describe their changes.

https://wiki.openstreetmap.org/wiki/API_v0.6#Notes_3

So we should not automatically generate the comment of changeset, we need users to enter comment.

**Comment by LaoshuBaby** [comment]
> So we should not automatically generate the comment of changeset, we need users to enter comment.

We can still generate a comment suggestion (display in gray, like those text), user can decide whether to use it or enter comment themselves. (like what osmand did.)

![图片](https://user-images.githubusercontent.com/42690037/159105358-bb8898fa-9a8d-4c41-9848-51cb26ec71e7.png)

**Comment by yuiseki** [comment]
Nice idea! That sounds very convenient!
